### ISSUE TITLE
Build Failed for IOS - ld: framework not found Stripe3DS2

### ISSUE THREAD

**Issue by muzammil22** [jonasbark/flutter_stripe_payment#222]
ld: framework not found Stripe3DS2
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to
    14.0.99. (in target 'firebase_core' from project 'Pods')
    warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to
    14.0.99. (in target 'Flutter' from project 'Pods')

I ran the example code as as followed the instructions in the medium article. Getting this error even if I fix all the warnings. Any help would be appreciated.

**Comment by liqiang1995** [comment]
I got the same bug.
did you fix it?

**Comment by aguerola** [comment]
Same error here!
Is there a workaround? I am stuck here and not able to update my ios app anymore because of this

**Comment by muzammil22** [comment]
I download the repo. It has the example app code. I tested my logic in the example app. But it isn't a fix still.

**Comment by liqiang1995** [comment]
I fixed it.
If you upgrade your cocoa pod version to the latest version, it will work well.
Good luck.

**Comment by muzammil22** [comment]
How do you update your cocoa pods version ?

**Comment by liqiang1995** [comment]
sudo gem install cocoapods

**Comment by muzammil22** [comment]
Great. thanks alot.

**Comment by aguerola** [comment]
I already have the latest version of cocoapods (1.10.0),  and the issue persists.
Any other ideas?

**Comment by ady-rangga-phtn** [comment]
I trying to change platform ios in podfile from 11.0 into 10.0, then can run successfully

**Comment by kjawadDeveloper** [comment]
Any solution

**Comment by kjawadDeveloper** [comment]
For me changing stripe_payment to 11.0 and ensuring all other dependencies are either 11 or above solved it for me

**Comment by sunnyp18** [comment]
> I trying to change platform ios in podfile from 11.0 into 10.0, then can run successfully

This worked for me too!

What is the negatives with moving down a global platform version? Surely this is better as more devices can run the app ?
